# Generated by Django 4.2.4 on 2023-09-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cacti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Olea Brassica", max_length=30)),
                ("image", models.FileField(upload_to="images/")),
            ],
            options={
                "verbose_name": "cactus",
                "verbose_name_plural": "cacti",
            },
        ),
    ]
