# Generated by Django 4.2.4 on 2023-09-27 03:31

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cacti",
            name="image_2",
            field=s3direct.fields.S3DirectField(default="image.jpg"),
        ),
    ]
