# Generated by Django 4.2.4 on 2023-09-27 03:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_cacti_image_2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cacti",
            name="image_2",
        ),
    ]
