# Generated by Django 4.2.4 on 2023-09-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_remove_cacti_image_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cacti",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
